service: typescript-serverless-template

package:
  patterns: ${file(./slsignore.yml)}

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-plugin-log-retention
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false

custom:
  esbuild:
    bundle: true
    sourcemap: true
    minify: false
    packager: yarn
    exclude: ['aws-sdk']
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['**/*.test.ts']
  serverless-offline:
    port: 3000
  logRetentionInDays: 14

functions:
  hello:
    handler: src/functions/hello.handle
    events:
      - http:
          path: /hello
          method: GET
          cors: true